/* Exercise 01. */

use movies;

-- 1.
SELECT NAME
FROM MOVIESTAR
WHERE NAME IN (SELECT NAME
		FROM MOVIEEXEC
			WHERE NETWORTH > 10000000);

-- 2.
SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN (SELECT NAME
		FROM MOVIEEXEC);

-- 3.
SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE = 'Star Wars');

-- 4.
/*
SELECT NAME, (SELECT TITLE FROM MOVIE WHERE PRODUCERC# = me.CERT#) AS moviesProduced
FROM MOVIEEXEC as me
WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Merv Griffin');
*/

SELECT TITLE, NAME
FROM MOVIEEXEC as me JOIN MOVIE
ON PRODUCERC# = CERT#
WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Merv Griffin');
