/* Exercise 03. */

use ships;

-- 1.
SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS = (SELECT TOP 1 NUMGUNS FROM CLASSES ORDER BY NUMGUNS DESC);

-- OR

SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES);

-- 2.
SELECT DISTINCT SHIPS.CLASS
FROM SHIPS JOIN OUTCOMES
ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'sunk';

-- OR

SELECT DISTINCT CLASS
FROM SHIPS
WHERE SHIPS.NAME IN (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'sunk');

-- 3.
SELECT NAME, CLASS
FROM SHIPS
WHERE CLASS IN (SELECT CLASS FROM CLASSES WHERE BORE = 16);

-- 4.
SELECT BATTLE
FROM OUTCOMES
WHERE SHIP IN (SELECT NAME FROM SHIPS WHERE CLASS = 'Kongo');

--5.
SELECT C1.CLASS, NAME
FROM SHIPS JOIN CLASSES AS C1
ON SHIPS.CLASS = C1.CLASS
WHERE C1.NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES AS C2 WHERE C1.BORE = C2.BORE)
ORDER BY C1.CLASS ASC;
